/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface LoadingBar {
    }
}
declare global {
    interface HTMLLoadingBarElement extends Components.LoadingBar, HTMLStencilElement {
    }
    var HTMLLoadingBarElement: {
        prototype: HTMLLoadingBarElement;
        new (): HTMLLoadingBarElement;
    };
    interface HTMLElementTagNameMap {
        "loading-bar": HTMLLoadingBarElement;
    }
}
declare namespace LocalJSX {
    interface LoadingBar {
    }
    interface IntrinsicElements {
        "loading-bar": LoadingBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "loading-bar": LocalJSX.LoadingBar & JSXBase.HTMLAttributes<HTMLLoadingBarElement>;
        }
    }
}
